enum EndpointContexts {
    CREATE_PAYMENT_METHOD = "CRPM",
    DELETE_PAYMENT_METHOD = "DLPM",
    GET_ALL_PRODUCTS = "GEAP",
    GET_PRODUCT = "GEPR",
    GET_PRODUCT_INVENTORY_IN_STORE = "GPIS",
    GET_PRODUCT_WITH_STOCK_IN_STORE = "GPWS",
    CREATE_PRODUCT = "CRPR",
    UPDATE_PRODUCT = "UPPR",
    CREATE_ORDER = "CROR",
    GET_STORE = "GEST",
    GET_STORE_INVENTORIES = "GESN",
    CREATE_ADDRESS = "CRAD",
    DELETE_ADDRESS = "DLAD",
    CREATE_CLIENT = "CRCL",
    CREATE_EMPLOYEE = "CREM",
    UPDATE_EMPLOYEE = "UPEM",
    CREATE_STORE = "CSTR",
    UPDATE_STORE = "USTR",
    GET_ORDERS_BY_EMPLOYEE_AND_STATUS = "GOES"
}

export { EndpointContexts };
