enum EndpointContexts {
    CREATE_PAYMENT_METHOD = "CRPM",
    DELETE_PAYMENT_METHOD = "DLPM",
    GET_ALL_PRODUCTS = "GEAP",
    CREATE_PRODUCT = "CRPR",
    UPDATE_PRODUCT = "UPPR",
    CREATE_ORDER = "CROR",
    GET_STORE_INVENTORIES = "GESN",
    CREATE_ADDRESS = "CRAD",
    DELETE_ADDRESS = "DLAD",
    CREATE_CLIENT = "CRCL"
}

export { EndpointContexts };